Repository KHU-RETURN/return-community-backend, pull requests merged in 2023-07, with the labels that each got.

#11 회원가입 기능 구현
  src/main/java/com/khureturn/community/config/ConfigureImp.java
  src/main/java/com/khureturn/community/config/CorsConfig.java
  src/main/java/com/khureturn/community/controller/MemberController.java
  src/main/java/com/khureturn/community/domain/Member.java
  src/main/java/com/khureturn/community/domain/common/UploadType.java
  src/main/java/com/khureturn/community/dto/MemberRequestDto.java
  src/main/java/com/khureturn/community/dto/MemberResponseDto.java
  src/main/java/com/khureturn/community/exception/ErrCode.java
  src/main/java/com/khureturn/community/exception/Media/InvalidMediaType.java
  src/main/java/com/khureturn/community/exception/Member/FailedMemberInfo.java
  src/main/java/com/khureturn/community/exception/Member/InvalidMemberInfoException.java
  src/main/java/com/khureturn/community/repository/MemberRepository.java
  src/main/java/com/khureturn/community/service/MediaService.java
  src/main/java/com/khureturn/community/service/MemberService.java
  src/main/java/com/khureturn/community/service/Oauth2LoginService.java
  src/main/resources/application.yml
Labels: ✨ New Feature

#13 로그아웃 기능 구현
  build.gradle
  src/main/java/com/khureturn/community/CommunityApplication.java
  src/main/java/com/khureturn/community/controller/MemberController.java
  src/main/java/com/khureturn/community/controller/Oauth2LoginController.java
  src/main/java/com/khureturn/community/security/JwtAuthenticationFilter.java
  src/main/java/com/khureturn/community/security/JwtProvider.java
  src/main/java/com/khureturn/community/service/AccountService.java
  src/main/java/com/khureturn/community/service/Oauth2LogoutService.java
  src/main/resources/application.yml
Labels: 🔒 Security, ✨ New Feature

#17 feat: Add Diary Features
  build.gradle
  src/main/java/com/khureturn/community/CommunityApplication.java
  src/main/java/com/khureturn/community/controller/DiaryCommentController.java
  src/main/java/com/khureturn/community/controller/DiaryController.java
  src/main/java/com/khureturn/community/controller/DiaryLikeController.java
  src/main/java/com/khureturn/community/controller/DiaryScrapController.java
  src/main/java/com/khureturn/community/domain/Member.java
  src/main/java/com/khureturn/community/domain/base/BaseEntity.java
  src/main/java/com/khureturn/community/domain/diary/Diary.java
  src/main/java/com/khureturn/community/domain/diary/DiaryComment.java
  src/main/java/com/khureturn/community/domain/diary/DiaryFile.java
  src/main/java/com/khureturn/community/domain/notice/Notice.java
  src/main/java/com/khureturn/community/dto/DiaryCommentRequestDto.java
  src/main/java/com/khureturn/community/dto/DiaryCommentResponseDto.java
  src/main/java/com/khureturn/community/dto/DiaryConverter.java
  src/main/java/com/khureturn/community/dto/DiaryRequestDto.java
  src/main/java/com/khureturn/community/dto/DiaryResponseDto.java
  src/main/java/com/khureturn/community/exception/DuplicateInsertionException.java
  src/main/java/com/khureturn/community/exception/NotFoundException.java
  src/main/java/com/khureturn/community/repository/DiaryCommentRepository.java
  src/main/java/com/khureturn/community/repository/DiaryFileRepository.java
  src/main/java/com/khureturn/community/repository/DiaryLikeRepository.java
  src/main/java/com/khureturn/community/repository/DiaryRepository.java
  src/main/java/com/khureturn/community/repository/DiaryScrapRepository.java
  src/main/java/com/khureturn/community/repository/MemberRepository.java
  src/main/java/com/khureturn/community/service/DiaryCommentService.java
  src/main/java/com/khureturn/community/service/DiaryFileService.java
  src/main/java/com/khureturn/community/service/DiaryLikeService.java
  src/main/java/com/khureturn/community/service/DiaryScrapService.java
  src/main/java/com/khureturn/community/service/DiaryService.java
  src/main/java/com/khureturn/community/service/DiaryServiceImpl.java
  src/main/java/com/khureturn/community/service/MemberService.java
  src/main/resources/application.yml
Labels: ✨ New Feature

#19 refactor: Refactoring OAuth Login
  src/main/java/com/khureturn/community/controller/Oauth2LoginController.java
  src/main/java/com/khureturn/community/service/AccountService.java
  src/main/resources/application-jwt.yml
  src/main/resources/application.yml
Labels: 🔒 Security, 🚨 Emergency

#20 Feat/14 profile detail
  src/main/java/com/khureturn/community/controller/MemberController.java
  src/main/java/com/khureturn/community/dto/MemberResponseDto.java
  src/main/java/com/khureturn/community/security/UserDetails/PrincipalDetails.java
  src/main/java/com/khureturn/community/service/MemberService.java
Labels: 🔒 Security, ✨ New Feature

#23 chore: The environmental variables of the application are separated i…
  src/main/resources/application-jwt.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ♻️ Refactoring

#24 CI/CD: Deploy Continuous Deployment
  .github/workflows/gradle.yml
  src/main/resources/application-prod.yml
Labels: ✨ New Feature

#26 feat: Add Diary Sort Features
  build.gradle
  medias/스크린샷 2023-03-06 214344.png
  src/main/java/com/khureturn/community/controller/DiaryCommentController.java
  src/main/java/com/khureturn/community/controller/DiaryController.java
  src/main/java/com/khureturn/community/dto/DiaryCommentRequestDto.java
  src/main/java/com/khureturn/community/dto/DiaryCommentResponseDto.java
  src/main/java/com/khureturn/community/dto/DiaryConverter.java
  src/main/java/com/khureturn/community/dto/DiaryRequestDto.java
  src/main/java/com/khureturn/community/dto/DiaryResponseDto.java
  src/main/java/com/khureturn/community/dto/MemberResponseDto.java
  src/main/java/com/khureturn/community/repository/DiaryRepository.java
  src/main/java/com/khureturn/community/service/DiaryCommentService.java
  src/main/java/com/khureturn/community/service/DiaryService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✨ New Feature

#29 fix: Fix Build Error
  src/main/java/com/khureturn/community/controller/DiaryCommentController.java
  src/main/java/com/khureturn/community/controller/DiaryController.java
  src/main/java/com/khureturn/community/domain/Member.java
  src/main/java/com/khureturn/community/domain/diary/Diary.java
  src/main/java/com/khureturn/community/domain/exam/Exam.java
  src/main/java/com/khureturn/community/domain/notice/Notice.java
Labels: 🚑 Hot-Fix

#31 refoctor: Migrate the database to mysql
  build.gradle
  src/main/resources/application-prod.yml
Labels: ❗Important, ♻️ Refactoring

#33 fix: Change the function that automatically creates the database to a…
  src/main/resources/application-prod.yml
Labels: 🐛 Bug

#34 feat: Add Recomment Feature
  src/main/java/com/khureturn/community/controller/DiaryCommentController.java
  src/main/java/com/khureturn/community/domain/diary/DiaryComment.java
  src/main/java/com/khureturn/community/dto/DiaryCommentRequestDto.java
  src/main/java/com/khureturn/community/dto/DiaryCommentResponseDto.java
  src/main/java/com/khureturn/community/dto/DiaryConverter.java
  src/main/java/com/khureturn/community/repository/DiaryCommentRepository.java
  src/main/java/com/khureturn/community/repository/DiaryFileRepository.java
  src/main/java/com/khureturn/community/repository/DiaryLikeRepository.java
  src/main/java/com/khureturn/community/service/DiaryCommentService.java
  src/main/java/com/khureturn/community/service/DiaryFileService.java
  src/main/java/com/khureturn/community/service/DiaryLikeService.java
  src/main/java/com/khureturn/community/service/DiaryService.java
Labels: ✨ New Feature

#37 feat: modify member information
  src/main/java/com/khureturn/community/controller/MemberController.java
  src/main/java/com/khureturn/community/domain/Member.java
  src/main/java/com/khureturn/community/dto/MemberRequestDto.java
  src/main/java/com/khureturn/community/service/MediaService.java
  src/main/java/com/khureturn/community/service/MemberService.java
Labels: ✨ New Feature

#41 fix: Correct the incorrect return value of the response to googleSub.
  src/main/java/com/khureturn/community/security/UserInfoDto/UserInfoDto.java
  src/main/java/com/khureturn/community/service/AccountService.java
Labels: 🚨 Emergency, 🚑 Hot-Fix

#42 feat: Add Nickname field
  src/main/java/com/khureturn/community/controller/MemberController.java
  src/main/java/com/khureturn/community/domain/Member.java
  src/main/java/com/khureturn/community/dto/MemberRequestDto.java
  src/main/java/com/khureturn/community/dto/MemberResponseDto.java
  src/main/java/com/khureturn/community/exception/ErrCode.java
  src/main/java/com/khureturn/community/exception/Member/FailedMemberInfo.java
  src/main/java/com/khureturn/community/repository/MemberRepository.java
  src/main/java/com/khureturn/community/service/AccountService.java
  src/main/java/com/khureturn/community/service/MemberService.java
Labels: ✨ New Feature

#46 fix: Change credentials to true with respect to CORS
  src/main/java/com/khureturn/community/config/ConfigureImp.java
  src/main/java/com/khureturn/community/config/WebSecurityConfig.java
Labels: 🚑 Hot-Fix

#49 refactor : Include Jwt in the response header
  src/main/java/com/khureturn/community/config/ConfigureImp.java
  src/main/java/com/khureturn/community/config/WebSecurityConfig.java
  src/main/java/com/khureturn/community/controller/MemberController.java
  src/main/java/com/khureturn/community/security/JwtAuthenticationFilter.java
  src/main/java/com/khureturn/community/security/JwtProvider.java
  src/main/java/com/khureturn/community/service/AccountService.java
  src/main/java/com/khureturn/community/service/MemberService.java
Labels: 🔒 Security, ♻️ Refactoring
