Repository KHU-RETURN/return-community-backend, pull requests merged in 2023-08, with the labels that each got.

#53 feat: Add Discord logback bot with webhook
  .github/workflows/gradle.yml
  build.gradle
  src/main/resources/application-prod.yml
  src/main/resources/logback.xml
Labels: 🐛 Bug, ✨ New Feature, 🚨 Emergency

#55 feat: Add Exam Features
  src/main/java/com/khureturn/community/CommunityApplication.java
  src/main/java/com/khureturn/community/controller/ExamController.java
  src/main/java/com/khureturn/community/domain/exam/Exam.java
  src/main/java/com/khureturn/community/domain/exam/ExamFile.java
  src/main/java/com/khureturn/community/dto/ExamRequestDto.java
  src/main/java/com/khureturn/community/dto/ExamResponseDto.java
  src/main/java/com/khureturn/community/repository/MemberRepository.java
  src/main/java/com/khureturn/community/service/ExamFileService.java
  src/main/java/com/khureturn/community/service/ExamService.java
Labels: ✨ New Feature

#57 feat: Add Swagger Feature
  build.gradle
  src/main/java/com/khureturn/community/config/SwaggerConfig.java
  src/main/java/com/khureturn/community/config/WebSecurityConfig.java
  src/main/java/com/khureturn/community/controller/DiaryCommentController.java
  src/main/java/com/khureturn/community/controller/DiaryController.java
  src/main/java/com/khureturn/community/controller/ExamController.java
  src/main/java/com/khureturn/community/dto/converter/DiaryConverter.java
  src/main/java/com/khureturn/community/dto/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/khureturn/community/service/DiaryService.java
  src/main/webapp/WEB-INF/static/examFiles/2bf582ab-d63a-414e-9473-858260c6e02b_스크린샷 2023-08-05 오후 5.41.07.png
Labels: ✨ New Feature

#60 feat: Add Exam Features
  src/main/java/com/khureturn/community/controller/DiaryController.java
  src/main/java/com/khureturn/community/controller/ExamController.java
  src/main/java/com/khureturn/community/domain/diary/DiaryFile.java
  src/main/java/com/khureturn/community/domain/exam/Exam.java
  src/main/java/com/khureturn/community/dto/converter/DiaryConverter.java
  src/main/java/com/khureturn/community/repository/ExamLikeRepository.java
  src/main/java/com/khureturn/community/repository/ExamRepository.java
  src/main/java/com/khureturn/community/repository/ExamScrapRepository.java
  src/main/java/com/khureturn/community/service/DiaryFileService.java
  src/main/java/com/khureturn/community/service/DiaryService.java
  src/main/java/com/khureturn/community/service/ExamFileService.java
  src/main/java/com/khureturn/community/service/ExamService.java
Labels: ✨ New Feature

#62 feat: Add Exam Detail Features
  src/main/java/com/khureturn/community/CommunityApplication.java
  src/main/java/com/khureturn/community/controller/DiaryController.java
  src/main/java/com/khureturn/community/controller/DiaryLikeController.java
  src/main/java/com/khureturn/community/controller/DiaryScrapController.java
  src/main/java/com/khureturn/community/controller/ExamController.java
  src/main/java/com/khureturn/community/controller/ExamLikeController.java
  src/main/java/com/khureturn/community/controller/ExamScrapController.java
  src/main/java/com/khureturn/community/domain/diary/DiaryLike.java
  src/main/java/com/khureturn/community/domain/exam/Exam.java
  src/main/java/com/khureturn/community/dto/ExamResponseDto.java
  src/main/java/com/khureturn/community/repository/DiaryRepository.java
  src/main/java/com/khureturn/community/repository/ExamLikeRepository.java
  src/main/java/com/khureturn/community/repository/ExamRepository.java
  src/main/java/com/khureturn/community/repository/ExamScrapRepository.java
  src/main/java/com/khureturn/community/repository/MemberRepository.java
  src/main/java/com/khureturn/community/service/DiaryCommentService.java
  src/main/java/com/khureturn/community/service/DiaryLikeService.java
  src/main/java/com/khureturn/community/service/DiaryScrapService.java
  src/main/java/com/khureturn/community/service/DiaryService.java
  src/main/java/com/khureturn/community/service/ExamFileService.java
  src/main/java/com/khureturn/community/service/ExamLikeService.java
  src/main/java/com/khureturn/community/service/ExamScrapService.java
  src/main/java/com/khureturn/community/service/ExamService.java
  src/main/java/com/khureturn/community/service/MemberService.java
Labels: ✨ New Feature

#65 hotfix: change swagger server url
  src/main/java/com/khureturn/community/config/SwaggerConfig.java
Labels: 🚑 Hot-Fix

#67 fix: Fix Diary
  src/main/java/com/khureturn/community/controller/DiaryController.java
  src/main/java/com/khureturn/community/controller/DiaryLikeController.java
  src/main/java/com/khureturn/community/controller/DiaryScrapController.java
  src/main/java/com/khureturn/community/controller/ExamController.java
  src/main/java/com/khureturn/community/domain/Member.java
  src/main/java/com/khureturn/community/domain/base/BaseEntity.java
  src/main/java/com/khureturn/community/domain/diary/DiaryLike.java
  src/main/java/com/khureturn/community/domain/exam/Exam.java
  src/main/java/com/khureturn/community/domain/notice/Notice.java
  src/main/java/com/khureturn/community/domain/notice/NoticeComment.java
  src/main/java/com/khureturn/community/domain/notice/NoticeFile.java
  src/main/java/com/khureturn/community/domain/notice/NoticeLike.java
  src/main/java/com/khureturn/community/domain/notice/NoticeScrap.java
  src/main/java/com/khureturn/community/dto/converter/DiaryConverter.java
  src/main/java/com/khureturn/community/repository/ExamFileRepository.java
  src/main/java/com/khureturn/community/service/DiaryFileService.java
  src/main/java/com/khureturn/community/service/DiaryService.java
  src/main/java/com/khureturn/community/service/ExamFileService.java
Labels: 🐛 Bug, 🚑 Hot-Fix

#69 fix: Fix DiaryComment
  src/main/java/com/khureturn/community/controller/ExamController.java
  src/main/java/com/khureturn/community/repository/DiaryCommentRepository.java
  src/main/java/com/khureturn/community/service/DiaryCommentService.java
  src/main/java/com/khureturn/community/service/ExamFileService.java
  src/main/java/com/khureturn/community/service/ExamService.java
Labels: 🚑 Hot-Fix

#72 fix: Fix DiaryComment
  src/main/java/com/khureturn/community/controller/ExamController.java
  src/main/java/com/khureturn/community/domain/exam/ExamFile.java
  src/main/java/com/khureturn/community/service/DiaryCommentService.java
  src/main/java/com/khureturn/community/service/DiaryService.java
  src/main/java/com/khureturn/community/service/ExamFileService.java
  src/main/java/com/khureturn/community/service/ExamScrapService.java
  src/main/java/com/khureturn/community/service/ExamService.java
Labels: 🚑 Hot-Fix

#73 fix: Fix MemberDto
  src/main/java/com/khureturn/community/dto/DiaryCommentResponseDto.java
  src/main/java/com/khureturn/community/service/DiaryCommentService.java
Labels: 🚑 Hot-Fix

#75 fix: Fix DiaryRecomment
  src/main/java/com/khureturn/community/controller/DiaryCommentController.java
  src/main/java/com/khureturn/community/controller/ExamController.java
  src/main/java/com/khureturn/community/dto/DiaryCommentResponseDto.java
  src/main/java/com/khureturn/community/repository/DiaryCommentRepository.java
  src/main/java/com/khureturn/community/service/DiaryCommentService.java
Labels: 🚑 Hot-Fix

#76 fix: Fix Like, Scrap, Viewcount
  src/main/java/com/khureturn/community/controller/DiaryController.java
  src/main/java/com/khureturn/community/controller/DiaryLikeController.java
  src/main/java/com/khureturn/community/controller/ExamController.java
  src/main/java/com/khureturn/community/service/DiaryLikeService.java
  src/main/java/com/khureturn/community/service/DiaryScrapService.java
  src/main/java/com/khureturn/community/service/DiaryService.java
  src/main/java/com/khureturn/community/service/ExamLikeService.java
  src/main/java/com/khureturn/community/service/ExamScrapService.java
  src/main/java/com/khureturn/community/service/ExamService.java
Labels: 🚑 Hot-Fix

#77 fix: Fix FileUpload
  src/main/java/com/khureturn/community/service/DiaryFileService.java
  src/main/java/com/khureturn/community/service/DiaryService.java
Labels: 🚑 Hot-Fix
